apply plugin: 'com.android.application'

android {
    signingConfigs {
        config {
            storeFile file('/home/mikael/Documents/Programming/MusicPlayerRemote/Google play/keystore')
            keyAlias 'prezz'
        }
    }
    compileSdk = 36
    defaultConfig {
        applicationId 'net.prezz.mpr'
        minSdk 35
        targetSdk 36
        versionCode 143
        versionName '1.143.0'
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }
    productFlavors {
    }
    namespace = 'net.prezz.mpr'
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.viewpager2:viewpager2:1.1.0'
    implementation 'org.apache.commons:commons-csv:1.14.1'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-Xlint:deprecation'
    options.deprecation = true
}